# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='attending_adventure',
            field=models.ManyToManyField(default='', related_name='pirates_attending_adventures_list', to='log_reg_adventure_app.User'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='hosting_adventure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pirates_hosting_adventures_list', to='log_reg_adventure_app.User'),
        ),
    ]
