# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0002_auto_20190713_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adventure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
